INSERT INTO `b___an_aus` (`id`, `wert`) VALUES (1, 'JA');
INSERT INTO `b___an_aus` (`id`, `wert`) VALUES (2, 'NEIN');

-- Setze bool-Werte für die an_aus Tabelle
UPDATE `b___an_aus` SET `bool`=1 WHERE `id`=1;
UPDATE `b___an_aus` SET `bool`=0 WHERE `id`=2;

INSERT INTO `b___geschlecht` (`id`, `auswahl`) VALUES (1, 'männlich');
INSERT INTO `b___geschlecht` (`id`, `auswahl`) VALUES (2, 'weiblich');
INSERT INTO `b___geschlecht` (`id`, `auswahl`) VALUES (3, 'divers');

INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (0, 'Administrator', 'Automatisch bei der Installation hinzugefügt', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (1, 'Regional-Admin', 'Admintätigkeiten im Regionalverband', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (2, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (3, 'Mitglied (D)', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (4, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (5, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (6, 'Landesverband (A)', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (7, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (8, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (9, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (10, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (11, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (12, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (13, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (14, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (15, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (16, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (17, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (18, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (19, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (20, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (21, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (22, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (23, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (24, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (25, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (26, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (27, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (28, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (29, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (30, '', '', 1);
INSERT INTO `y_roles` (`bit`, `name`, `role_comment`, `role_active`) VALUES (31, '', '', 1);

INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (1, 'Aerobic', 100);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (2, 'Angeln', 200);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (3, 'Aquagymnastik', 300);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (4, 'Badminton', 400);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (5, 'Basketball', 500);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (6, 'Beachvolleyball', 600);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (7, 'Billard', 700);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (8, 'Bogenschiessen', 800);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (9, 'Reiten', 900);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (10, 'Boule /  Boccia / Petanque', 910);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (11, 'Bosseln', 920);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (12, 'Bowling', 1100);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (13, 'Boxen', 1200);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (14, 'Brettspiele', 1300);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (15, 'Curling', 1400);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (16, 'Dart', 1500);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (17, 'Drachenboot', 1600);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (18, 'Eishockey', 1700);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (19, 'Eislaufen', 1800);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (20, 'Faustball', 1900);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (21, 'Fechten', 2000);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (22, 'Fitness', 2100);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (23, 'Frisbee', 2200);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (24, 'Fußball', 2300);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (25, 'Fussball - Halle', 2310);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (26, 'Fussball - Kleinfeld', 2320);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (27, 'Fussball - Grossfeld', 2330);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (28, 'Geräteturnen', 2400);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (29, 'Golf', 2500);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (30, 'Gymnastik', 2600);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (31, 'Handball', 2700);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (32, 'Hockey', 2800);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (33, 'Indoorclimbing', 2900);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (34, 'Feuerwehrsport', 3000);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (35, 'Jogging', 3100);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (36, 'Kampfsport', 3200);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (37, 'Judo', 3205);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (38, 'Jiu Jitsu', 3210);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (39, 'Ju-Jutsu', 3215);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (40, 'Karate', 3220);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (41, 'Kendo', 3230);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (42, 'Kickboxen', 3235);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (43, 'Krav Maga', 3240);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (44, 'Ringen', 3245);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (45, 'Teakwondo', 3250);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (46, 'Thai Bo', 3255);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (47, 'Wing Chun', 3260);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (48, 'Kanu', 3300);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (49, 'Kartenspiele', 3400);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (50, 'Skat', 3410);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (51, 'Bridge', 3420);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (52, 'Romme', 3430);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (53, 'Kartsport', 3500);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (54, 'Kegeln', 3600);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (55, 'Bohle', 3610);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (56, 'Schere', 3620);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (57, 'Asphalt', 3630);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (58, 'Klettern', 3700);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (59, 'Bouldern', 3710);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (60, 'Kraftsport', 3800);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (61, 'Laufen', 3900);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (62, 'Leichtathletik', 4000);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (63, 'Motorsport', 4100);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (64, 'Mountenbike', 4200);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (65, 'Nordic Walking', 4300);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (66, 'Orientierungslauf', 4400);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (67, 'Pferdesport', 4500);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (68, 'Pilates', 4600);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (69, 'Radsport', 4700);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (70, 'Rudern', 4800);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (71, 'Schach', 4900);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (72, 'Schwimmen', 5000);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (73, 'Segeln', 5100);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (74, 'Selbstverteidigung', 5200);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (75, 'Skisport', 5400);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (76, 'Deutsches Sportabzeichen', 5500);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (77, 'BGM-Sport', 5550);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (78, 'Schießsport', 5600);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (79, 'Squash', 5700);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (80, 'Streetball', 5800);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (81, 'Surfen', 5900);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (82, 'Tanzsport', 6000);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (83, 'Tauchen', 6100);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (84, 'Tennis', 6200);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (85, 'Tischfussball', 6300);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (86, 'Tischtennis', 6400);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (87, 'Triathlon', 6500);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (88, 'Turmspringen', 6600);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (89, 'Volleyball', 6700);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (90, 'Walking', 6800);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (91, 'Wandern', 6900);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (92, 'Wintersport', 7000);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (93, 'X-Golf', 7100);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (94, 'Yoga', 7200);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (95, 'Zumba', 7300);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (96, 'B-Zahl', 7500);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (97, 'Weitere Sportarten', 7900);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (98, 'Passive', 8000);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (99, 'Aquarium/Terrarium', 8010);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (100, 'Foto/Film', 8020);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (101, 'Modellbau', 8030);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (102, 'Kochen', 8040);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (103, 'Kräuter', 8050);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (104, 'Musik', 8060);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (105, 'Pilze', 8070);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (106, 'Theater', 8080);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (107, 'Funktionäre', 8500);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (108, 'Vorstand', 8510);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (109, 'Helfer', 8520);
INSERT INTO `b___sportart` (`id`, `Sportart`, `Sportart_Nr`) VALUES (110, 'Sonstige Ballsportarten', 8530);

INSERT INTO `b_regionalverband` (id, `Verband`) VALUES (1, 'Dummy - bitte anpassen');
INSERT INTO `b_bsg` (`Verband`, `BSG`) VALUES (1, 'Dummy - bitte anpassen');


